### PR TITLE
Add RSSI to uat2json and uat2text output.

### PR DESCRIPTION
**Pull request by KeyserSoze1**
This is my attempt to get RSSI into dump978.  It's a bit of a mixture between the stratux fork and dump1090-mutability RSSI.  

It currently only affects uat2json and uat2text.  uat2esnt would be great but I'm not aware of anyway to include the information in what is sent.

It seems to be working fine here but would like to see a few more people use it and confirm what I'm seeing.

Also open to suggestions for improvements or corrections to anything that is found.

### CODE REVIEW

**Comment by KeyserSoze1** [comment]
Did not intend for the 2nd commit to come through for this pull request.  I had intended for that to be a separate pull request.  I wasn't thinking when I pushed that commit up to the same branch.  I'll move it to another request if you would like or if you would rather just have them in a single request that's fine also.

**Comment by SoNic1967** [comment]
I would be interested also in this. Especially if added to @jprochazka adsb-receiver.

**Comment by bottleworks** [comment]
OBJ still around????

**Comment by mutability** [comment]
Still around, but unfortunately dump978 maintenance is quite a long way down my todo list

**Comment by KeyserSoze1** [comment]
@mutability No worries.  Hopefully all is going well and you can take care of this when you get around to it.  In the meantime I have pushed my changes into master on my fork so anyone interested in RSSI from uat2json, uat2text, or uat2esnt can go grab that.

**Comment by SoNic1967** [comment]
5 months later... any news with this pull?

**Comment by kevinelliott** [comment]
Let's get this sucker merged in guys!

**Comment by jprochazka** [comment]
> @jprochazka any interest in including this feature and the other one added to this branch in your ads-b receiver project?

@KeyserSoze1 sure if pull request is excepted.
Will it be compatible with say dump1090-tools or will dump978-tools need to be created. :)

**Comment by KeyserSoze1** [comment]
@jprochazka The changes here are compatible with dump1090.  I have ran it successfully for some time with no issues.  

I haven't looked at this in a while but it looks like this pull request is missing a few of my final commits I made.  Anyone interested in trying this feature can just pull down my fork at https://github.com/KeyserSoze1/dump978 and try it for themselves.  I believe @mutability is probably a bit busy and it's unknown when he will get a chance to look at this.

**Comment by mutability** [comment]
You may want to look at https://github.com/flightaware/dump978/tree/dev
which has RSSI support and is where future development is happening

**Comment by jprochazka** [comment]
@mutability just took a look at the fa repository. Firstly thanks for adding the ability to build deb packages out of the box. However, I am not familiar with SoapySDR and as far as third party plugin support goes especially with the dump1090-fa/blade-rf issues on newer versions of Ubuntu I am leary... With this version are we going to run into issues with third party not necessary libraries causing issues with no support as is the case with dump1090-fa and blade-rf if not now but in the future.

**Comment by jprochazka** [comment]
@mutability just took a look at the fa repository. Firstly thanks for adding the ability to build deb packages out of the box!

As far as third party plugin support goes in this case SoapySDR, especially with the dump1090-fa/blade-rf being a huge issue, in particular new balde-rf builds not working with dump1090-fa I am leary... With this version are we going to run into issues with third party libraries causing issues with no support offered as is the case with dump1090-fa and blade-rf?  I am concerned that if not now but in the future this becomes an issue especially being someone has submitted a pull request not requiring said third party software which works with code you already wrote with **much** less code and overhead involved...

**Comment by jprochazka** [comment]
@mutability just took a look at the fa repository. Firstly thanks for adding the ability to build deb packages out of the box!

As far as third party dependencies are concerned, in this case SoapySDR, especially with the dump1090-fa/blade-rf being a huge issue, in particular new balde-rf builds not working with dump1090-fa I am leary... With this version are we going to run into issues with third party libraries causing issues with no support offered as is the case with dump1090-fa and blade-rf?  I am concerned that if not now but in the future this becomes an issue as well..

**Comment by jprochazka** [comment]
@mutability just took a look at the fa repository. Firstly thanks for adding the ability to build deb packages out of the box!

As far as third party dependencies are concerned, in this case SoapySDR, especially with the dump1090-fa/blade-rf being a huge issue, in particular new balde-rf builds not working with dump1090-fa I am leary... With this version are we going to run into issues with third party libraries causing issues with no support offered as is the case with dump1090-fa and blade-rf?  I am concerned that if not now but in the future this becomes an issue as well.

I may be sounding like an ass when it comes to third party libraries but it really annoys me I cannot build and run dump1090-fa even though I am sure there is an older version of blade-rf which works but no one will say which one it is. I am thinking this is the way it is going with FlightAware as of late...

**Comment by mutability** [comment]
The only bug report I have re bladerf is flightaware/dump1090#22 which got
closed after no response from the original reporter for a while. If you
have more information please reopen that issue and post it there. I cannot
support every possible system and I rely on users to report/diagnose
problems on systems other than what I have CI set up for.

As you are perhaps discovering, trying to support a wide range of systems
is a big task.

Re soapysdr, it insulates dump978 from the details of the underlying device
API so I would expect fewer problems here, not more.

>

**Pull request closed without merging**
