### PR TITLE
Portability for FlightRadar24 data upload

### PR DESCRIPTION
**Pull request by kjablonski**
For your review:

I have modified the uat2esnt program to accept a --df17 parameter to allow for FlightRadar24 to accept data from this program.  If TIS-B frames are sent from dump978 as downlinks, further modification may be necessary to filter these out before transmission

### CODE REVIEW

**Comment by mutability** [comment]
Given the trouble that generating synthetic mlat positions as DF17 has caused, I'm a bit reluctant to change dump978 to do the same when there's a reasonably good mapping already to DF18 etc. Can't FR24 teach their feeder about DF18 messages if they want to consume them?

**Comment by kjablonski** [comment]
Perhaps I misunderstand your comment but, I wasn't aware of an issue with UAT and MLAT.   My understanding of MLAT was a position was calculated from ModeS interrogation replies (DF5) on 1090MHz, and SSR does not listen to 978 for squawk codes.  I would think that since UAT is ADS-B out with positional data MLAT is irrelevent since UAT is already broadcasting location.

Unrelated:  Where did you find the specs for the CF/CA field of DF18/17, respectively?  I am unable to find anything regarding bits 6-8 of DF17 messages.

**Comment by mutability** [comment]
The issue with mlat was that mlat-client (https://github.com/mutability/mlat-client) can emit mlat positions as synthetic DF17 messages so they can be displayed by e.g. an unmodified dump1090. But in practice what has been happening is that those synthetic messages have been getting looped back in some cases and treated as if they were real ADS-B positions .. which they are not. This makes the various flight-aggregating sites unhappy.

In retrospect using DF18 for those synthetic mlat positions would have been a better choice that causes fewer problems (and I may switch mlat-client to use DF18 at some point).

So for dump978 I don't know if it is a good idea to start emitting DF17 as they might be mistaken for real 1090MHz ADS-B transmissions. With DF18 at least we can mark them explictly as retransmissions.

I'll see if I can dig up the CF/CA references for you, I have the appropriate spec somewhere..

**Comment by kjablonski** [comment]
Commit 4c6188a494cc6f93bd9d6821775290c206e68c7c resolves this issue

**Pull request closed without merging**
